# Generated by Django 5.0.4 on 2024-05-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nin',
        ),
    ]
