# Generated by Django 5.0.4 on 2024-05-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_remove_userdata_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'NIN',
                'verbose_name_plural': 'NiNs',
            },
        ),
        migrations.AlterModelOptions(
            name='nums',
            options={'verbose_name': 'user', 'verbose_name_plural': 'Nums'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Userdata', 'verbose_name_plural': 'Usersdata'},
        ),
        migrations.AlterField(
            model_name='nums',
            name='num',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='otherlinks',
            field=models.ManyToManyField(blank=True, to='main.otherlink'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sociallinks',
            field=models.ManyToManyField(blank=True, to='main.sociallink'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='nin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.nin'),
            preserve_default=False,
        ),
    ]
