# Generated by Django 5.0.4 on 2024-05-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_nin_alter_nums_options_alter_userdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherlink',
            old_name='text',
            new_name='display_text',
        ),
    ]
