# Generated by Django 5.0.4 on 2024-05-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='static//images/users'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='nin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nin'),
        ),
    ]
