# Generated by Django 5.0.4 on 2024-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sociallink_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ristriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ristriction',
                'verbose_name_plural': 'Ristrictions',
            },
        ),
    ]
