# Generated by Django 5.0.4 on 2024-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ristriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ristriction',
            name='type',
            field=models.CharField(choices=[('All users', 'All'), ('All except', 'Allexecpt')], default='all', max_length=100),
            preserve_default=False,
        ),
    ]
