# Generated by Django 5.0.4 on 2024-05-10 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_ristriction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ristriction',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ristriction',
            name='type',
            field=models.CharField(choices=[('all', 'All Users'), ('except', 'All Except'), ('only', 'Only')], max_length=100),
        ),
    ]
