# Generated by Django 5.0.4 on 2024-05-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ristriction_user_alter_ristriction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='restrictions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ristriction'),
        ),
    ]
