# Generated by Django 5.0.4 on 2024-05-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_restrictions_userdata_ristrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ristrictions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ristriction'),
        ),
    ]
