# Generated by Django 5.0.4 on 2024-05-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_userdata_ristrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
